name: NathanBurley2165
favicon: null
layout_spectrum: 0.60848
typography_spectrum: 0.21369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4285f4'
    - '#ea4335'
    - '#fbbc05'
    - '#704b43'
  brandStrength: 0.1875
  lightness: 0.2199016623198986
  saturation: 0.18524051178246737
  rhythmicContrast: 0.7040610816329718
purpose: []
