name: NathanBurley2165
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5931
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f5ee'
    - '#10120f'
    - '#c2924a'
    - '#60492a'
    - '#d06108'
  brandStrength: 0
  lightness: 0.2199016623198986
  saturation: 0.18524051178246737
  rhythmicContrast: 0.7040610816329718
purpose: []
